# Generated by Django 4.0.1 on 2022-09-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fullname',
        ),
    ]
