# Generated by Django 4.0.1 on 2022-09-03 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_rename_slots_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='public',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeter', to=settings.AUTH_USER_MODEL),
        ),
    ]
